[package]
name = "gvas"
description = "Crate for reading and writing UE4+ save files."
authors = ["localcc <work@localcc.cc>", "Scott Anderson"]
keywords = ["ue4", "unrealengine", "ue5", "gvas", "uasset"]
homepage = "https://github.com/localcc/gvas"
repository = "https://github.com/localcc/gvas"
readme = "README.md"
license = "MIT"
version = "0.11.0"
edition = "2024"

[dependencies]
binrw = "0.15.1"
chrono = "0.4.45"
modular-bitfield = "0.13.1"
thiserror = "2.0.18"
flate2 = { version="1.1.5", optional = true }

[features]
palworld = ["dep:flate2"]
