#![allow(unused)]

/// Custom serialization version for changes made in //UE5/Release-* stream
/// See: Engine/Source/Runtime/Core/Public/UObject/UE5ReleaseStreamObjectVersion.h
pub enum EUE5ReleaseStreamObjectVersion {
    BeforeCustomVersionWasAdded = 0,
    ReflectionMethodEnum,
    WorldPartitionActorDescSerializeHLODInfo,
    RemovingTessellation,
    LevelInstanceSerializeRuntimeBehavior,
    PoseAssetRuntimeRefactor,
    WorldPartitionActorDescSerializeActorFolderPath,
    HairStrandsVertexFormatChange,
    AddChaosMaxLinearAngularSpeed,
    PackedLevelInstanceVersion,
    PackedLevelInstanceBoundsFix,
    CustomPropertyAnimGraphNodesUseOptionalPinManager,
    TextFormatArgumentData64bitSupport,
    MaterialLayerStacksAreNotParameters,
    MaterialInterfaceSavedCachedData,
    AddClothMappingLODBias,
    AddLevelActorPackagingScheme,
    WorldPartitionActorDescSerializeAttachParent,
    ConvertedActorGridPlacementToSpatiallyLoadedFlag,
    ActorGridPlacementDeprecateDefaultValueFixup,
    PackedLevelActorUseWorldPartitionActorDesc,
    AddLevelActorFolders,
    RemoveSkeletalMeshLODModelBulkDatas,
    ExcludeBrightnessFromEncodedHDRCubemap,
    VolumetricCloudSampleCountUnification,
    PoseAssetRawDataGUID,
    ConvolutionBloomIntensity,
    WorldPartitionHLODActorDescSerializeHLODSubActors,
    LargeWorldCoordinates,
}
pub const GUID_UE5_RELEASE_STREAM: u128 = 0xDF6417798412ACA824BD4D46D89B5E42;

/// Custom serialization version for changes made in Dev-Editor stream.
/// See: Engine/Source/Runtime/Core/Public/UObject/EditorObjectVersion.h
pub enum EEditorObjectVersion {
    BeforeCustomVersionWasAdded = 0,
    GatheredTextProcessVersionFlagging,
    GatheredTextPackageCacheFixesV1,
    RootMetaDataSupport,
    GatheredTextPackageCacheFixesV2,
    TextFormatArgumentDataIsVariant,
    SplineComponentCurvesInStruct,
    ComboBoxControllerSupportUpdate,
    RefactorMeshEditorMaterials,
    AddedFontFaceAssets,
    UPropertryForMeshSection,
    WidgetGraphSchema,
    AddedBackgroundBlurContentSlot,
    StableUserDefinedEnumDisplayNames,
    AddedInlineFontFaceAssets,
    UPropertryForMeshSectionSerialize,
    FastWidgetTemplates,
    MaterialThumbnailRenderingChanges,
    NewSlateClippingSystem,
    MovieSceneMetaDataSerialization,
    GatheredTextEditorOnlyPackageLocId,
    AddedAlwaysSignNumberFormattingOption,
    AddedMaterialSharedInputs,
    AddedMorphTargetSectionIndices,
    SerializeInstancedStaticMeshRenderData,
    MeshDescriptionNewSerializationMovedToRelease,
    MeshDescriptionNewAttributeFormat,
    ChangeSceneCaptureRootComponent,
    StaticMeshDeprecatedRawMesh,
    MeshDescriptionBulkDataGuid,
    MeshDescriptionRemovedHoles,
    ChangedWidgetComponentWindowVisibilityDefault,
    CultureInvariantTextSerializationKeyStability,
    ScrollBarThicknessChange,
    RemoveLandscapeHoleMaterial,
    MeshDescriptionTriangles,
    ComputeWeightedNormals,
    SkeletalMeshBuildRefactor,
    SkeletalMeshMoveEditorSourceDataToPrivateAsset,
    NumberParsingOptionsNumberLimitsAndClamping,
    SkeletalMeshSourceDataSupport16bitOfMaterialNumber,
}
pub const GUID_EDITOR: u128 = 0x2E46BB41A231DA0BF49442E9E4B068ED;
